
export const Terms = () => {
    const Items = [
        {
            title: "1. Acceptance of Terms",
            description: "By accessing or using our services, you confirm that you have read, understood, and agree to these Terms, as well as our Privacy Policy. If you are using the services on behalf of an organization, you agree to these Terms on behalf of that organization."
        },
        {
            title: "2. Eligibility",
            description: "You must be at least 14 years old to use our services. By using the website, you warrant that you have the legal capacity to enter into these Terms."
        },
        {
            title: "3. User Responsibilities",
            description: "Data Accuracy: You are responsible for ensuring the accuracy and legality of any data (e.g., CSV files) uploaded to our platform.\nProhibited Content: You agree not to upload files that contain sensitive personal information, malicious code, or any unlawful material.\nUsage Limits: You will not use the services in any manner that disrupts, damages, or overburdens the platform."
        },
        {
            title: "4. Intellectual Property",
            description: "Ownership of Insights and Visualizations: The data insights, charts, and visualizations generated by our platform are for your use and are derived from the data you provide. However, the underlying technology and algorithms remain the sole property of ChartMind.\nLicense: By uploading data, you grant us a non-exclusive, royalty-free license to process your data for the purpose of generating insights and visualizations."
        },
        {
            title: "5. Data Privacy and Security",
            description: "We are committed to protecting your data. For more details, please refer to our Privacy Policy. While we implement industry-standard security measures, we cannot guarantee absolute security. By using our services, you acknowledge and accept this risk."
        },
        {
            title: "6. Service Limitations",
            description: "The insights and visualizations provided are based on automated algorithms and are intended for informational purposes only. We do not guarantee the accuracy, completeness, or reliability of the results.\nThe platform is provided on an “as-is” and “as-available” basis. We reserve the right to modify, suspend, or discontinue the service at any time without notice."
        },
        {
            title: "7. Prohibited Activities",
            description: "Use the platform for unlawful purposes.\nReverse-engineer or copy the service or its components.\nAttempt to gain unauthorized access to our systems."
        },
        {
            title: "8. Payment and Refunds",
            description: "Access advanced features with paid plans, adhering to our clear and fair refund policies."
        },
        {
            title: "9. Limitation of Liability",
            description: "To the fullest extent permitted by law, ChartMind is not liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from:\nYour use or inability to use the service.\nUnauthorized access to or alteration of your data."
        },
        {
            title: "10. Termination",
            description: "We may terminate or suspend your access to the services if you violate these Terms or engage in prohibited activities."
        },
        {
            title: "11. Changes to the Terms",
            description: "Stay informed about updates to our terms and policies for continued, seamless use of our services."
        },
        {
            title: "12. Governing Law",
            description: "Resolve disputes under the legal jurisdiction outlined, ensuring compliance with applicable laws."
        }
    ];
    
    return (
        <div className="relative  border-b border-neutral-800 min-h-[800px]">
            <h2 className="text-3xl sm:text-5xl lg:text-6xl mt-10 lg:mt-20 tracking wide">
                Terms of
                <span className="bg-gradient-to-r from-orange-500 to-orange-800 text-transparent bg-clip-text">
                    {" "} Service
                </span>
            </h2>
            <p className="text-md p-2 mb-20 text-neutral-500">
                Welcome to our cutting-edge data analytics platform, where we transform raw data into meaningful insights. Our mission is to empower businesses, professionals, and students by providing a seamless and powerful tool to explore, analyze, and visualize data like never before.
            </p>
            <div className="flex flex-wrap mt-10 lg:mt-20">
                {Items.map((item: any, index: number) => (
                    <div key={index} className="w-full sm-1/2 lg:w-1/3">
                        <div className="flex">
                            <div>
                                <h5 className="mt-1 mb-6 text-xl">
                                    {item.title}
                                </h5>
                                <ul className="text-md p-2 mb-20 text-neutral-500 list-disc pl-6">
                                    {item.description.split("\n").map((line: string, idx: number) => (
                                        <li key={idx}>
                                            {line}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};
